package edu.univalle.eisc

/**
 * @author ${user.name}
 */

import org.apache.spark.sql.functions._
import com.databricks.spark.corenlp.functions._
import org.apache.spark.SparkContext
import org.apache.spark.SparkContext._
import org.apache.spark.SparkConf

object HelloWorld {
  def main(args: Array[String]): Unit = {

    

    val conf = new SparkConf().setAppName("Simple Application").setMaster("spark://registro:7077")
    val sc = new SparkContext(conf)
    val sqlContext = new org.apache.spark.sql.SQLContext(sc)

    import sqlContext.implicits._

    val t0 = System.currentTimeMillis()
    val r = scala.util.Random
    val docs: List[String] = List(
      "The House, forced to vote a second time on the $1.5 trillion tax bill, moved swiftly to pass the final version on Wednesday, clearing the way for President Trump to sign into law the most sweeping tax overhaul in decades.House lawmakers approved the tax bill 224 to 201 on Wednesday, after being forced to vote on the bill again after last-minute revisions were made to the Senate bill, which passed that chamber 51 to 48 early Wednesday morning.The final House vote was essentially a formality, as the changes, which were made to comply with Senate budget rules, did not significantly alter the overall bill. But the need for a second vote gave ammunition to Democrats, who had already accused Republicans of trying to rush the tax overhaul through the House and Senate.We are five days away from Christmas, but it feels like Groundhog Day, said Representative Louise M. Slaughter, Democrat of New York, who denounced the process by which Republicans undertook their tax rewrite as “nothing short of an abomination.",
      "The overhaul drops the corporate rate to 21 percent, from 35 percent, as Republicans seek to boost American competitiveness and spur economic growth. In addition, it provides a tax break to owners of pass-through businesses, whose profits are taxed through the individual code.\n\nThe bill also cuts taxes for individuals, including a lower top rate of 37 percent, down from 39.6 percent. It nearly doubles the standard deduction and doubles the child tax credit, and it also doubles the size of inheritances shielded from estate taxation, to $22 million for married couples. But Republicans set the individual tax cuts to expire after 2025 in order to make the bill comply with budget rules.",
      "In a move that drew significant criticism from lawmakers from states with high taxes, the bill caps the deduction for state and local taxes at $10,000. Twelve House Republicans voted against the tax bill on both Tuesday and Wednesday, and 11 of those members were from California, New Jersey and New York, three states with high taxes.The bill also eliminates the Affordable Care Act’s requirement that most people have health insurance or pay a penalty, known as the individual mandate, providing Republicans with a victory on health care after their previous failure to repeal and replace President Barack Obama’s health law. It also opens the Arctic National Wildlife Refuge in Alaska to oil and gas drilling.",
      "Building a web of data via the Semantic Web requires consistency in how data are represented. In the Semantic Web, anyone can invent and express new concepts, but the universal Web can only emerge through tying concepts together (Berners-Lee, Hendler, & Lassila, 2001). Introductory texts on ontology development often list the ability to reuse existing ontologies as one of the key attractions of the Semantic Web (Allemang & Hendler, 2011). Adopting existing ontologies for a new application, however, requires substantial knowledge of Semantic Web principles and underlying technologies. Naïve approaches, such as simply selecting ontologies that match keywords of interest, can lead to Frankenstein ontologies that run afoul of good ontological engineering practices (Corcho, Poveda-Villalon, & Gomez-Perez, 2015).The EarthCollab project seeks to utilize the Semantic Web to advance geoscience research and the discovery of connections among research projects.",
      "Re-reading the details of the Tax Cuts and Jobs Act, I keep imagining life over on Earth II, where this bill being proposed by a President Romney or Kasich, to Democrats lead by Kirsten Gillibrand and Joe Manchin. Would there even be a debate?  Or would it pass the Senate 74-23, with a majority of Democratic support, as the 1986 tax-reform bill did?  The 1986 tax reform cut the top rate for those evil millionaires and billionaires Bernie Sanders loves to rail against down to a mere 28 percent—nearly 10 points lower than the top rate in this bill.",
      "This paper explores the effort of efficiently developing a local ontology while employing established ontologies that enhance connections to the broader community. The EarthCollab project, a collaboration between the University Corporation for Atmospheric Research (UCAR)/National Center for Atmospheric Research (NCAR), UNAVCO, and Cornell University, is using Semantic Web and linked data technologies to facilitate the coordination and organization of complex scientific projects, their communities, their tools, and their products. The EarthCollab partners are using the VIVO semantic software suite to enable more coherent discovery of distributed information and data for large multi-disciplinary scientific projects. To facilitate easier integration and data sharing across the geoscience community, the EarthCollab goal has been to reuse existing ontologies as much as possible when developing project ontologies and web applications. The questions this paper addresses are as follows",
      "It is possible to devise workflows (either production or exploratory) that exploit multiple systems by using extract-transform-and-load (ETL) techniques to move data from Spark to a system for graph processing and then back again for further processing. But this is time consuming and considerably complicates the workflows ETL complications are particularly challenging for exploratory workflows but they are also an issue for some production workflows where it may be more efficient to remain in the Spark environment. Also, moving in and out of a Spark environment requires additional programming skill and introduces the opportunity for error.",
	    "An Oval Office meeting involving President Trump and his top advisers on Wednesday devolved into a heated exchange between his former campaign manager and the White House political director, people briefed on the discussion said. The meeting centered on the midterm elections and came as Republicans face a daunting landscape next year, particularly after a bruising loss in the Alabama special election this month. It also came as the White House faces an expected string of departures from the West Wing, including that of a deputy chief of staff, Rick Dearborn, on Thursday. Mr. Dearborn, who was close to Jared Kushner and Ivanka Trump during the transition, had been overseeing a broad cross section of departments, including the political department, which was a source of contention during the meeting. The meeting prompted the political director, Bill Stepien, to call an official at the main political group supporting Mr. Trump, America First Policies, to say its counsel should be involved at future gatherings. It also underlined the turf battles and strategic disagreements that have long been characteristic of Mr. Trump’s circle, dating to his presidential campaign.",
	    "A White House spokeswoman declined to comment. The initial meeting included Mr. Trump; Mr. Stepien; John F. Kelly, the White House chief of staff; Kellyanne Conway, the White House counselor; and Hope Hicks, the communications director. Also in attendance were Corey Lewandowski, Mr. Trump’s former campaign manager, and Brad Parscale, both of whom are advisers to America First Policies. Continue reading the main story The Trump White House The historic moments, head-spinning developments and inside-the-White House intrigue Mr. Lewandowski aggressively criticized the Republican National Committee, as well as several White House departments, five people briefed on the discussion said. He told the president that his government staff and political advisers at the party committee were doing little to help him, three of the people briefed on the meeting said. He pointed to, among other thinned-out departments, the Office of Public Liaison. One attendee, speaking on the condition of anonymity because the discussion was intended to be private, said Mr. Lewandowski took pointed aim at the political operation led by Mr. Stepien. Another attendee insisted that Mr. Lewandowski lashed out at nearly every department but the political shop.",
	    "America First Policies exists for one reason: to support the president of the United States and his agenda, Mr. Walsh said. Everything else is just noise. We commend the president for getting tax reform passed and making America great again. Mr. Stepien appears to be the latest front in a rotating cast of advisers surrounding Mr. Trump over the last three years. A series of election defeats, coupled with legislative inertia through much of the year, has made him the target of criticism, primarily from outside the White House. But Mr. Stepien has his defenders, among them Mr. Kelly, who two attendees at the Oval Office meeting said was put off by Mr. Lewandowski’s criticism. So were other attendees of the meeting, according to two people present, although Mr. Trump did not appear to be one of them.",
	    "Thousands of students who say they have been swindled by predatory for-profit universities will soon learn whether their loans will be forgiven by the Education Department, but under a new Trump administration policy, some students who expected full loan forgiveness may only receive partial relief. The education secretary, Betsy DeVos, announced Wednesday that the department will have responded to more than 20,000 so-called borrower-defense claims filed by students from Corinthian Colleges, a defunct for-profit chain that spurred a federal crackdown on for-profit colleges.  The claims, part of nearly 100,000 that have amassed and stalled under the Trump administration, include 12,900 approvals and 8,600 denials.  The notifications are the first step that Ms. DeVos has taken to address widespread abuses in the for-profit sector that have left students buried in debt with seemingly worthless degrees and little recourse except for seeking debt relief from the federal government.  But the announcement that the department would begin discharging claims this week came with a caveat. The departments improved process would allow some students to recoup only partial damages if they are found to be gainfully employed, Ms. DeVos said.",
	    "Policy experts said that the decision unfairly penalized students who had managed to succeed despite being swindled. It was unfair, they added, to change the discharge process midstream, especially for Corinthian Colleges students whose applications were handled by two different administrations.  In other words, two students who attended the same program and were lied to in the same way by their school, and even who may have applied for a borrower-defense claim on the same day, could wind up with vastly different amounts of relief, wrote Clare McCann, a federal policy expert at the New America Foundation and a former Obama official.  The new system, which Ms. DeVos said replaced an all or nothing approach, would determine loan forgiveness on a tiered system.  Students whose current earnings are less than 50 percent of their peers from a comparable program will receive full relief, and students whose earnings are at 50 percent or more of their peers will receive proportionally tiered relief to compensate for the difference and make them whole."
		)
    for( a <- 1 to 20000) {
      val input = Seq((1, docs(r.nextInt(10)))).toDF("id", "text")

      val output = input
        .select(cleanxml('text).as('doc))
        .select(explode(ssplit('doc)).as('sen))
        .select('sen, tokenize('sen).as('words), ner('sen).as('nerTags))

      output.show(truncate = true)
    }
      val t1 = System.currentTimeMillis()

    println("Elapsed time: " + (t1 - t0) + "s")

  }
}